spring.application.name=projeto

# Configuração do MySQL
spring.datasource.url=jdbc:mysql://localhost:3306/ecommerce?createDatabaseIfNotExist=true&serverTimezone=America/Sao_Paulo
spring.datasource.username=usuario
spring.datasource.password=123@Mudar
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# JPA / Hibernate
spring.jpa.hibernate.ddl-auto=create
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# Dialeto
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect